import { cn } from "@/lib/utils";

/**
 * The Kobo brand mark. Single source of truth — every place the logo appears
 * renders this, so there is never more than one logo implementation.
 *
 *   variant="full"  → the dotted-K symbol + "OBO" wordmark. Use wherever there
 *                     is horizontal room (page headers, sidebar, wide cards).
 *   variant="mark"  → the dotted-K symbol only. Use in constrained spots
 *                     (compact headers, small centred brand slots, avatars).
 *
 * The assets are the supplied `KOBOLOGO.png`, cropped to a tight bounding box
 * and pre-tinted to the app's ink token value (`--kobo-ink` / `--landing-ink`
 * = #0b1f24) — NOT the old green. Transparent PNG, so it sits cleanly on any
 * surface. Regenerated by `scripts/build-brand-assets.mjs` if the token or the
 * source logo changes.
 *
 * Consumers set the height (`h-6`, `h-14`, …) and leave the width `auto`; the
 * intrinsic width/height attributes keep the aspect ratio and avoid layout
 * shift.
 */

const ASSET = {
  full: { src: "/brand/kobo-logo.png", width: 1591, height: 491 },
  mark: { src: "/brand/kobo-mark.png", width: 481, height: 491 },
} as const;

export function KoboLogo({
  variant = "full",
  className,
  priority = false,
}: {
  variant?: "full" | "mark";
  className?: string;
  /** Set on the above-the-fold logo (auth screen, first paint) so it isn't lazy-loaded. */
  priority?: boolean;
}) {
  const a = ASSET[variant];
  return (
    // eslint-disable-next-line @next/next/no-img-element -- a static, tiny, non-optimizable brand asset; next/image adds no value and its config surface is avoided here
    <img
      src={a.src}
      width={a.width}
      height={a.height}
      alt="Kobo"
      draggable={false}
      decoding="async"
      loading={priority ? "eager" : "lazy"}
      fetchPriority={priority ? "high" : "auto"}
      className={cn("w-auto select-none", className)}
    />
  );
}
